name: Daily True Crime Briefing

on:
  schedule:
    # Runs daily at 9:00 AM PT 
    # Note: GitHub Actions uses UTC time
    # 9 AM PT = 4 PM UTC (Standard Time) / 5 PM UTC (Daylight Time)
    # Using 5 PM UTC to cover Daylight Saving Time
    - cron: '0 17 * * *'
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  send-briefing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run daily briefing
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      run: python daily_briefing.py
    
    - name: Upload logs (if needed for debugging)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: briefing-logs
        path: '*.log'
        retention-days: 7
